//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HIB.Outlook.SQLite
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttachmentInfo
    {
        public long AttachmentId { get; set; }
        public Nullable<long> ClientId { get; set; }
        public Nullable<long> ActivityId { get; set; }
        public string FileExtension { get; set; }
        public string FileName { get; set; }
        public Nullable<long> ParentFolderId { get; set; }
        public string ParentFolderName { get; set; }
        public Nullable<long> FolderId { get; set; }
        public string FolderName { get; set; }
        public Nullable<long> SubFolderId { get; set; }
        public string SubFolderName { get; set; }
        public string PolicyCode { get; set; }
        public string PolicyType { get; set; }
        public string PolicyYear { get; set; }
        public string ClientAccessible { get; set; }
        public string EmailFromAddress { get; set; }
        public string EmailToAddress { get; set; }
        public string Subject { get; set; }
        public string ReceivedDate { get; set; }
        public string AttachmentFilePath { get; set; }
        public string Description { get; set; }
        public Nullable<long> IsPushedToEpic { get; set; }
        public Nullable<long> IsAttachDelete { get; set; }
        public string Identifier { get; set; }
        public Nullable<long> IsActiveClient { get; set; }
        public Nullable<long> IsActiveActivity { get; set; }
        public string DescFrom { get; set; }
        public string CreatedDate { get; set; }
        public string ModifiedDate { get; set; }
        public string EmployeeCode { get; set; }
        public string AttachmentMailBody { get; set; }
        public Nullable<long> IsDeletedFromZFolder { get; set; }
        public string EmailFromDisplayName { get; set; }
        public string EmailToDisplayName { get; set; }
        public string EmailCCAddress { get; set; }
        public string EmailCCDisplayName { get; set; }
        public string ActivityGuid { get; set; }
        public string UserName { get; set; }
        public string DomainName { get; set; }
        public Nullable<long> IsEpicPushInProgress { get; set; }
        public string AttachmentIdentifier { get; set; }
    }
}
