//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HIB.Outlook.SQLite
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIBOPActivityOpportunity
    {
        public int UniqOpportunity { get; set; }
        public long UniqEntity { get; set; }
        public string OppDesc { get; set; }
        public Nullable<System.DateTime> TargetedDate { get; set; }
        public Nullable<System.DateTime> ActualDate { get; set; }
        public Nullable<int> UniqSalesTeam { get; set; }
        public Nullable<int> UniqEmployeeOwner { get; set; }
        public Nullable<int> UniqOpportunityStage { get; set; }
        public string OwnerName { get; set; }
        public string SalesTeam { get; set; }
        public string SalesManager { get; set; }
        public string Stage { get; set; }
        public Nullable<int> Flags { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual HIBOPClient HIBOPClient { get; set; }
    }
}
