//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HIB.Outlook.SQLite
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIBOPEmployeeAgency
    {
        public long EAId { get; set; }
        public long UniqEntity { get; set; }
        public string EmployeeName { get; set; }
        public string LookupCode { get; set; }
        public int UniqAgency { get; set; }
        public string AgencyCode { get; set; }
        public string BranchCode { get; set; }
        public string AgencyName { get; set; }
        public int UniqBranch { get; set; }
        public string BranchName { get; set; }
        public int UniqDepartment { get; set; }
        public string DepartmentCode { get; set; }
        public string Departmetname { get; set; }
        public int UniqProfitCenter { get; set; }
        public string ProfitCenterCode { get; set; }
        public string ProfitCenterNAme { get; set; }
    
        public virtual HIBOPClient HIBOPClient { get; set; }
    }
}
