//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HIB.Outlook.SQLite
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIBOPPolicyLineType
    {
        public long UniqCdPolicyLineType { get; set; }
        public string CdPolicyLineTypeCode { get; set; }
        public string PolicyLineTypeDesc { get; set; }
        public Nullable<long> Status { get; set; }
        public System.DateTime InsertedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
