//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HIB.Outlook.SQLite
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HIBOutlookEntities : DbContext
    {
        public HIBOutlookEntities()
            : base("name=HIBOutlookEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HIBOPActivityAccount> HIBOPActivityAccounts { get; set; }
        public virtual DbSet<HIBOPActivityBill> HIBOPActivityBills { get; set; }
        public virtual DbSet<HIBOPActivityCertificate> HIBOPActivityCertificates { get; set; }
        public virtual DbSet<HIBOPActivityClientContact> HIBOPActivityClientContacts { get; set; }
        public virtual DbSet<HIBOPActivityEvidence> HIBOPActivityEvidences { get; set; }
        public virtual DbSet<HIBOPActivityLine> HIBOPActivityLines { get; set; }
        public virtual DbSet<HIBOPActivityLookupDetail> HIBOPActivityLookupDetails { get; set; }
        public virtual DbSet<HIBOPActivityMasterMarketing> HIBOPActivityMasterMarketings { get; set; }
        public virtual DbSet<HIBOPActivityOpportunity> HIBOPActivityOpportunities { get; set; }
        public virtual DbSet<HIBOPActivityOwnerList> HIBOPActivityOwnerLists { get; set; }
        public virtual DbSet<HIBOPActivityService> HIBOPActivityServices { get; set; }
        public virtual DbSet<HIBOPActivityTransaction> HIBOPActivityTransactions { get; set; }
        public virtual DbSet<HIBOPAddActivity> HIBOPAddActivities { get; set; }
        public virtual DbSet<HIBOPCarrierSubmission> HIBOPCarrierSubmissions { get; set; }
        public virtual DbSet<HIBOPClaim> HIBOPClaims { get; set; }
        public virtual DbSet<HIBOPClient> HIBOPClients { get; set; }
        public virtual DbSet<HIBOPClientEmployee> HIBOPClientEmployees { get; set; }
        public virtual DbSet<HIBOPCommonLookup> HIBOPCommonLookups { get; set; }
        public virtual DbSet<HIBOPEmployee> HIBOPEmployees { get; set; }
        public virtual DbSet<HIBOPEmployeeAgency> HIBOPEmployeeAgencies { get; set; }
        public virtual DbSet<HIBOPFavourite> HIBOPFavourites { get; set; }
        public virtual DbSet<HIBOPFolderAttachment> HIBOPFolderAttachments { get; set; }
        public virtual DbSet<HIBOPPolicy> HIBOPPolicies { get; set; }
        public virtual DbSet<HIBOPPolicyLineType> HIBOPPolicyLineTypes { get; set; }
        public virtual DbSet<HIBOPSyncLog> HIBOPSyncLogs { get; set; }
        public virtual DbSet<HIBOPSyncLogUserDetail> HIBOPSyncLogUserDetails { get; set; }
        public virtual DbSet<HIBOPErrorLog> HIBOPErrorLogs { get; set; }
        public virtual DbSet<HIBOPOutlookPluginLog> HIBOPOutlookPluginLogs { get; set; }
        public virtual DbSet<HIBOPActivityList> HIBOPActivityLists { get; set; }
        public virtual DbSet<AttachmentInfo> AttachmentInfoes { get; set; }
        public virtual DbSet<HIBOPActivity> HIBOPActivities { get; set; }
        public virtual DbSet<HIBOPActivityEmployee> HIBOPActivityEmployees { get; set; }
    }
}
