//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HIB.Outlook.SQLite
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIBOPFavourite
    {
        public long FavId { get; set; }
        public string FavouriteName { get; set; }
        public string UniqEmployee { get; set; }
        public long UniqEntity { get; set; }
        public long IsActiveClient { get; set; }
        public Nullable<long> UniqActivity { get; set; }
        public long IsClosedActivity { get; set; }
        public string PolicyYear { get; set; }
        public string PolicyType { get; set; }
        public string DescriptionType { get; set; }
        public string Description { get; set; }
        public Nullable<long> FolderId { get; set; }
        public Nullable<long> SubFolder1Id { get; set; }
        public Nullable<long> SubFolder2Id { get; set; }
        public string ClientAccessibleDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ActivityGuid { get; set; }
    
        public virtual HIBOPClient HIBOPClient { get; set; }
    }
}
