//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HIB.Outlook.SQLite
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIBOPClient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HIBOPClient()
        {
            this.HIBOPActivityAccounts = new HashSet<HIBOPActivityAccount>();
            this.HIBOPActivityBills = new HashSet<HIBOPActivityBill>();
            this.HIBOPActivityCertificates = new HashSet<HIBOPActivityCertificate>();
            this.HIBOPActivityClientContacts = new HashSet<HIBOPActivityClientContact>();
            this.HIBOPActivityEvidences = new HashSet<HIBOPActivityEvidence>();
            this.HIBOPActivityLines = new HashSet<HIBOPActivityLine>();
            this.HIBOPActivityLookupDetails = new HashSet<HIBOPActivityLookupDetail>();
            this.HIBOPActivityMasterMarketings = new HashSet<HIBOPActivityMasterMarketing>();
            this.HIBOPActivityOpportunities = new HashSet<HIBOPActivityOpportunity>();
            this.HIBOPActivityServices = new HashSet<HIBOPActivityService>();
            this.HIBOPActivityTransactions = new HashSet<HIBOPActivityTransaction>();
            this.HIBOPCarrierSubmissions = new HashSet<HIBOPCarrierSubmission>();
            this.HIBOPClaims = new HashSet<HIBOPClaim>();
            this.HIBOPClientEmployees = new HashSet<HIBOPClientEmployee>();
            this.HIBOPEmployeeAgencies = new HashSet<HIBOPEmployeeAgency>();
            this.HIBOPFavourites = new HashSet<HIBOPFavourite>();
            this.HIBOPPolicies = new HashSet<HIBOPPolicy>();
            this.HIBOPOutlookPluginLogs = new HashSet<HIBOPOutlookPluginLog>();
            this.HIBOPActivities = new HashSet<HIBOPActivity>();
        }
    
        public long UniqEntity { get; set; }
        public string LookupCode { get; set; }
        public string NameOf { get; set; }
        public string PrimaryContactName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string StateCode { get; set; }
        public string StateName { get; set; }
        public string PostalCode { get; set; }
        public string CountryCode { get; set; }
        public string Country { get; set; }
        public string Status { get; set; }
        public System.DateTime InsertedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string AgencyCode { get; set; }
        public string AgencyName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HIBOPActivityAccount> HIBOPActivityAccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HIBOPActivityBill> HIBOPActivityBills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HIBOPActivityCertificate> HIBOPActivityCertificates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HIBOPActivityClientContact> HIBOPActivityClientContacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HIBOPActivityEvidence> HIBOPActivityEvidences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HIBOPActivityLine> HIBOPActivityLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HIBOPActivityLookupDetail> HIBOPActivityLookupDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HIBOPActivityMasterMarketing> HIBOPActivityMasterMarketings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HIBOPActivityOpportunity> HIBOPActivityOpportunities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HIBOPActivityService> HIBOPActivityServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HIBOPActivityTransaction> HIBOPActivityTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HIBOPCarrierSubmission> HIBOPCarrierSubmissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HIBOPClaim> HIBOPClaims { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HIBOPClientEmployee> HIBOPClientEmployees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HIBOPEmployeeAgency> HIBOPEmployeeAgencies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HIBOPFavourite> HIBOPFavourites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HIBOPPolicy> HIBOPPolicies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HIBOPOutlookPluginLog> HIBOPOutlookPluginLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HIBOPActivity> HIBOPActivities { get; set; }
    }
}
