//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HIB.Outlook.SQLite
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIBOPActivity
    {
        public int UniqActivity { get; set; }
        public long UniqEntity { get; set; }
        public Nullable<int> UniqActivityCode { get; set; }
        public string ActivityCode { get; set; }
        public string DescriptionOf { get; set; }
        public string UniqCdPolicyLineType { get; set; }
        public string PolicyNumber { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public string Status { get; set; }
        public System.DateTime InsertedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public Nullable<int> UniqAgency { get; set; }
        public Nullable<int> UniqBranch { get; set; }
        public Nullable<int> UniqDepartment { get; set; }
        public Nullable<int> UniqProfitCenter { get; set; }
        public Nullable<int> UniqAssociatedItem { get; set; }
        public string AssociationType { get; set; }
        public string OwnerCode { get; set; }
        public string OwnerDescription { get; set; }
        public Nullable<int> UniqPolicy { get; set; }
        public Nullable<int> UniqLine { get; set; }
        public Nullable<int> UniqClaim { get; set; }
        public Nullable<System.DateTime> LossDate { get; set; }
        public string PolicyDescription { get; set; }
        public string LineCode { get; set; }
        public string LineDescription { get; set; }
        public string ICO { get; set; }
        public Nullable<System.DateTime> LineEffectiveDate { get; set; }
        public Nullable<System.DateTime> LineExpirationDate { get; set; }
    
        public virtual HIBOPClient HIBOPClient { get; set; }
    }
}
