//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HIB.Outlook.SQLite
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIBOPActivityEmployee
    {
        public long UniqEmployee { get; set; }
        public string EmployeeLookupCode { get; set; }
        public Nullable<long> UniqEntity { get; set; }
        public Nullable<long> UniqActivity { get; set; }
    }
}
