//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HIB.Outlook.SQLite
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIBOPOutlookPluginLog
    {
        public long LogId { get; set; }
        public string UniqId { get; set; }
        public string UniqEmployee { get; set; }
        public long UniqEntity { get; set; }
        public int UniqActivity { get; set; }
        public string PolicyYear { get; set; }
        public string PolicyType { get; set; }
        public string DescriptionType { get; set; }
        public string Description { get; set; }
        public Nullable<long> FolderId { get; set; }
        public Nullable<long> SubFolder1Id { get; set; }
        public Nullable<long> SubFolder2Id { get; set; }
        public string EmailAction { get; set; }
        public Nullable<int> Version { get; set; }
        public System.DateTime InsertedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string EmailSubject { get; set; }
        public Nullable<long> Status { get; set; }
        public Nullable<long> AttachmentInfoId { get; set; }
        public string ClientAccessibleDate { get; set; }
        public string ClientCode { get; set; }
        public string ErrorMessage { get; set; }
    
        public virtual HIBOPClient HIBOPClient { get; set; }
    }
}
