//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HIB.Outlook.SQLite
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIBOPClaim
    {
        public long UniqEntity { get; set; }
        public int UniqClaim { get; set; }
        public string ClaimCode { get; set; }
        public string ClaimName { get; set; }
        public Nullable<System.DateTime> LossDate { get; set; }
        public Nullable<System.DateTime> ReportedDate { get; set; }
        public Nullable<int> ClaimNumber { get; set; }
        public string CompanyClaimNumber { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public Nullable<int> Flags { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual HIBOPClient HIBOPClient { get; set; }
    }
}
