//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HIB.Outlook.SQLite
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIBOPSyncLogUserDetail
    {
        public long Id { get; set; }
        public string EmployeeLookupcode { get; set; }
        public long SyncLogId { get; set; }
        public string SyncLogField { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
    
        public virtual HIBOPSyncLog HIBOPSyncLog { get; set; }
    }
}
