IF EXISTS ( SELECT 'X' FROM SYS.INDEXES WHERE NAME ='HIBOPEmployeeAgency_NDX1')
BEGIN
DROP INDEX HIBOPEmployeeAgency.HIBOPEmployeeAgency_NDX1;
END
GO
CREATE NONCLUSTERED INDEX HIBOPEmployeeAgency_NDX1 ON HIBOPEmployeeAgency(UniqEntity);
GO