IF EXISTS ( SELECT 'X' FROM SYS.INDEXES WHERE NAME ='HIBOPActvityOwnerList_IDX1')
BEGIN
	DROP INDEX HIBOPActvityOwnerList.HIBOPActvityOwnerList_IDX1;
END
GO

CREATE UNIQUE CLUSTERED INDEX HIBOPActvityOwnerList_IDX1 on HIBOPActvityOwnerList (UniqEntity);
GO