IF EXISTS ( SELECT 'X' FROM SYSOBJECTS WHERE XTYPE='PK' AND NAME ='HIBOPCid_PK')
BEGIN
	ALTER TABLE HIBOPClient DROP CONSTRAINT HIBOPCid_PK;
END
GO
ALTER TABLE HIBOPClient
ADD CONSTRAINT HIBOPCid_PK PRIMARY KEY CLUSTERED  ([OPCid] ASC);
GO
