

IF EXISTS ( SELECT 'X' FROM SYSOBJECTS WHERE XTYPE='PK' AND NAME ='HIBOPProfitCenter_PK')
BEGIN
	ALTER TABLE HIBOPProfitCenter DROP CONSTRAINT HIBOPProfitCenter_PK;
END
GO
ALTER TABLE HIBOPProfitCenter
ADD CONSTRAINT HIBOPProfitCenter_PK PRIMARY KEY CLUSTERED  (UniqProfitCenter);
GO


