

IF EXISTS ( SELECT 'X' FROM SYSOBJECTS WHERE XTYPE='PK' AND NAME ='HIBOPClient_PK')
BEGIN
	ALTER TABLE HIBOPClient DROP CONSTRAINT HIBOPClient_PK;
END
GO
ALTER TABLE HIBOPClient
ADD CONSTRAINT HIBOPClient_PK PRIMARY KEY CLUSTERED  (UniqEntity);
GO
