

IF EXISTS ( SELECT 'X' FROM SYSOBJECTS WHERE XTYPE='PK' AND NAME ='HIBOPFolderAttachment_PK')
BEGIN
	ALTER TABLE HIBOPFolderAttachment DROP CONSTRAINT HIBOPFolderAttachment_PK;
END
GO
ALTER TABLE HIBOPFolderAttachment
ADD CONSTRAINT HIBOPFolderAttachment_PK PRIMARY KEY CLUSTERED  (FolderId);
GO
