

IF EXISTS ( SELECT 'X' FROM SYSOBJECTS WHERE XTYPE='PK' AND NAME ='HIBOPBranch_PK')
BEGIN
	ALTER TABLE HIBOPBranch DROP CONSTRAINT HIBOPBranch_PK;
END
GO
ALTER TABLE HIBOPBranch
ADD CONSTRAINT HIBOPBranch_PK PRIMARY KEY CLUSTERED  (UniqBranch);
GO


