
IF EXISTS ( SELECT 'X' FROM SYSOBJECTS WHERE XTYPE='PK' AND NAME ='HIBOPClaim_PK')
BEGIN
	ALTER TABLE HIBOPClaim DROP CONSTRAINT HIBOPClaim_PK;
END
GO
ALTER TABLE HIBOPClaim
ADD CONSTRAINT HIBOPClaim_PK PRIMARY KEY CLUSTERED  (UniqClaim);
GO


