
IF EXISTS ( SELECT 'X' FROM SYSOBJECTS WHERE XTYPE='PK' AND NAME ='UniqCdPolicyLineType_PK')
BEGIN
	ALTER TABLE HIBOPPolicyLineType DROP CONSTRAINT UniqCdPolicyLineType_PK;
END
GO
ALTER TABLE HIBOPPolicyLineType
ADD CONSTRAINT UniqCdPolicyLineType_PK PRIMARY KEY CLUSTERED  ([UniqCdPolicyLineType] ASC);
GO

